export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const STORE_LOGGED_IN_USER = 'STORE_LOGGED_IN_USER'

export const VALIDATE_ACCESS = 'VALIDATE_ACCESS';

export const GET_VIEW2_DATA_REQUEST = 'GET_VIEW2_DATA_REQUEST';
export const GET_VIEW2_DATA_SUCCESS = 'GET_VIEW2_DATA_SUCCESS';
export const GET_VIEW2_DATA_FAILURE = 'GET_VIEW2_DATA_FAILURE';

export const GET_INITIAL_DATA = 'GET_INITIAL_DATA';

export const INSERT_MOVEMENTS_REQUEST = "INSERT_MOVEMENTS_REQUEST";
export const INSERT_MOVEMENTS_SUCCESS = "INSERT_MOVEMENTS_SUCCESS";
export const INSERT_MOVEMENTS_FAILURE = "INSERT_MOVEMENTS_FAILURE";

export const GET_MOVEMENTS_REQUEST = "GET_MOVEMENTS_REQUEST";
export const GET_MOVEMENTS_SUCCESS = "GET_MOVEMENTS_SUCCESS";
export const GET_MOVEMENTS_FAILURE = "GET_MOVEMENTS_FAILURE";
export const CLEAN_MOVEMENTS_LIST = "CLEAN_MOVEMENTS_LIST";

export const DELETE_MOVEMENT_REQUEST = "DELETE_MOVEMENT_REQUEST";
export const DELETE_MOVEMENT_SUCCESS = "DELETE_MOVEMENT_SUCCESS";
export const DELETE_MOVEMENT_FAILURE = "DELETE_MOVEMENT_FAILURE";