export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const STORE_LOGGED_IN_USER = 'STORE_LOGGED_IN_USER'

export const VALIDATE_ACCESS = 'VALIDATE_ACCESS';

export const GET_VIEW2_DATA_REQUEST = 'GET_VIEW2_DATA_REQUEST';
export const GET_VIEW2_DATA_SUCCESS = 'GET_VIEW2_DATA_SUCCESS';
export const GET_VIEW2_DATA_FAILURE = 'GET_VIEW2_DATA_FAILURE';

export const GET_INITIAL_DATA = 'GET_INITIAL_DATA';

export const INSERT_MOVEMENTS_REQUEST = "INSERT_MOVEMENTS_REQUEST";
export const INSERT_MOVEMENTS_SUCCESS = "INSERT_MOVEMENTS_SUCCESS";
export const INSERT_MOVEMENTS_FAILURE = "INSERT_MOVEMENTS_FAILURE";

export const GET_MOVEMENTS_REQUEST = "GET_MOVEMENTS_REQUEST";
export const GET_MOVEMENTS_SUCCESS = "GET_MOVEMENTS_SUCCESS";
export const GET_MOVEMENTS_FAILURE = "GET_MOVEMENTS_FAILURE";
export const CLEAN_MOVEMENTS_LIST = "CLEAN_MOVEMENTS_LIST";

export const DELETE_MOVEMENT_REQUEST = "DELETE_MOVEMENT_REQUEST";
export const DELETE_MOVEMENT_SUCCESS = "DELETE_MOVEMENT_SUCCESS";
export const DELETE_MOVEMENT_FAILURE = "DELETE_MOVEMENT_FAILURE";

export const GET_TYPE_DOCUMENTS_REQUEST = "GET_TYPE_DOCUMENTS_REQUEST";
export const GET_TYPE_DOCUMENTS_SUCCESS = "GET_TYPE_DOCUMENTS_SUCCESS";
export const GET_TYPE_DOCUMENTS_FAILURE = "GET_TYPE_DOCUMENTS_FAILURE";

export const GET_CORRELATIVE_MAX_REQUEST = "GET_CORRELATIVE_MAX_REQUEST";
export const GET_CORRELATIVE_MAX_SUCCESS = "GET_CORRELATIVE_MAX_SUCCESS";

export const USER_BOSS_OFFICE_REQUEST = "USER_BOSS_OFFICE_REQUEST";
export const USER_BOSS_OFFICE_SUCCESS = "USER_BOSS_OFFICE_SUCCESS";

export const GET_CIRCULAR_DOCUMENTS_REQUEST = "GET_CIRCULAR_DOCUMENTS_REQUEST";
export const GET_CIRCULAR_DOCUMENTS_SUCCESS = "GET_CIRCULAR_DOCUMENTS_SUCCESS";
export const GET_CIRCULAR_DOCUMENTS_FAILURE = "GET_CIRCULAR_DOCUMENTS_FAILURE";

export const GET_CIRCULAR_DETAILS_REQUEST = "GET_CIRCULAR_DETAILS_REQUEST";
export const GET_CIRCULAR_DETAILS_SUCCESS = "GET_CIRCULAR_DETAILS_SUCCESS";
export const GET_CIRCULAR_DETAILS_FAILURE = "GET_CIRCULAR_DETAILS_FAILURE";

export const CREATE_CIRCULAR_DOCUMENTS_REQUEST = "CREATE_CIRCULAR_DOCUMENTS_REQUEST";
export const CREATE_CIRCULAR_DOCUMENTS_SUCCESS = "CREATE_CIRCULAR_DOCUMENTS_SUCCESS";
export const CREATE_CIRCULAR_DOCUMENTS_FAILURE = "CREATE_CIRCULAR_DOCUMENTS_FAILURE";

export const EDIT_CIRCULAR_DOCUMENTS_REQUEST = "EDIT_CIRCULAR_DOCUMENTS_REQUEST";
export const EDIT_CIRCULAR_DOCUMENTS_SUCCESS = "EDIT_CIRCULAR_DOCUMENTS_SUCCESS";
export const EDIT_CIRCULAR_DOCUMENTS_FAILURE = "EDIT_CIRCULAR_DOCUMENTS_FAILURE";

export const DELETE_INTERN_DOCUMENT_REQUEST = "DELETE_INTERN_DOCUMENT_REQUEST";
export const DELETE_INTERN_DOCUMENT_SUCCESS = "DELETE_INTERN_DOCUMENT_SUCCESS";
export const DELETE_INTERN_DOCUMENT_FAILURE = "DELETE_INTERN_DOCUMENT_FAILURE";

export const GET_USER_MOVEMENTS_BY_OFFICE_REQUEST = "GET_USER_MOVEMENTS_BY_OFFICE_REQUEST";
export const GET_USER_MOVEMENTS_BY_OFFICE_SUCCESS = "GET_USER_MOVEMENTS_BY_OFFICE_SUCCESS";
export const GET_USER_MOVEMENTS_BY_OFFICE_FAILURE = "GET_USER_MOVEMENTS_BY_OFFICE_FAILURE";

export const GET_ADMIN_MOVEMENTS_BY_OFFICE_REQUEST = "GET_ADMIN_MOVEMENTS_BY_OFFICE_REQUEST";
export const GET_ADMIN_MOVEMENTS_BY_OFFICE_SUCCESS = "GET_ADMIN_MOVEMENTS_BY_OFFICE_SUCCESS";
export const GET_ADMIN_MOVEMENTS_BY_OFFICE_FAILURE = "GET_ADMIN_MOVEMENTS_BY_OFFICE_FAILURE";

export const GET_ADMIN_INTERN_DOCUMENTS_REQUEST = "GET_ADMIN_INTERN_DOCUMENTS_REQUEST";
export const GET_ADMIN_INTERN_DOCUMENTS_SUCCESS = "GET_ADMIN_INTERN_DOCUMENTS_SUCCESS";
export const GET_ADMIN_INTERN_DOCUMENTS_FAILURE = "GET_ADMIN_INTERN_DOCUMENTS_FAILURE";

export const CONFIRM_DOCUMENTS_REQUEST = "CONFIRM_DOCUMENTS_REQUEST";
export const CONFIRM_DOCUMENTS_SUCCESS = "CONFIRM_DOCUMENTS_SUCCESS";
export const CONFIRM_DOCUMENTS_FAILURE = "CONFIRM_DOCUMENTS_FAILURE";

export const GET_MOVEMENTS_BY_ASSIGNED_TO_REQUEST = "GET_MOVEMENTS_BY_ASSIGNED_TO_REQUEST";
export const GET_MOVEMENTS_BY_ASSIGNED_TO_SUCCESS = "GET_MOVEMENTS_BY_ASSIGNED_TO_SUCCESS";
export const GET_MOVEMENTS_BY_ASSIGNED_TO_FAILURE = "GET_MOVEMENTS_BY_ASSIGNED_TO_FAILURE";

export const DERIVE_DOCUMENTS_REQUEST= "DERIVE_DOCUMENTS_REQUEST";
export const DERIVE_DOCUMENTS_SUCCESS= "DERIVE_DOCUMENTS_SUCCESS";
export const DERIVE_DOCUMENTS_FAILURE= "DERIVE_DOCUMENTS_FAILURE";

export const DERIVE_ASSIGNED_DOCUMENTS_REQUEST= "DERIVE_ASSIGNED_DOCUMENTS_REQUEST";
export const DERIVE_ASSIGNED_DOCUMENTS_SUCCESS= "DERIVE_ASSIGNED_DOCUMENTS_SUCCESS";
export const DERIVE_ASSIGNED_DOCUMENTS_FAILURE= "DERIVE_ASSIGNED_DOCUMENTS_FAILURE";

export const GENERATE_RESPONSE_TO_MOVEMENT_REQUEST = "GENERATE_RESPONSE_TO_MOVEMENT_REQUEST";
export const GENERATE_RESPONSE_TO_MOVEMENT_SUCCESS = "GENERATE_RESPONSE_TO_MOVEMENT_SUCCESS";
export const GENERATE_RESPONSE_TO_MOVEMENT_FAILURE = "GENERATE_RESPONSE_TO_MOVEMENT_FAILURE";

export const GENERATE_RESPONSE_TO_MOVEMENT_ADMIN_REQUEST = "GENERATE_RESPONSE_TO_MOVEMENT_ADMIN_REQUEST";
export const GENERATE_RESPONSE_TO_MOVEMENT_ADMIN_SUCCESS = "GENERATE_RESPONSE_TO_MOVEMENT_ADMIN_SUCCESS";
export const GENERATE_RESPONSE_TO_MOVEMENT_ADMIN_FAILURE = "GENERATE_RESPONSE_TO_MOVEMENT_ADMIN_FAILURE";

export const CREATE_INTERN_DOCUMENTS_REQUEST = "CREATE_INTERN_DOCUMENTS_REQUEST";
export const CREATE_INTERN_DOCUMENTS_SUCCESS = "CREATE_INTERN_DOCUMENTS_SUCCESS";
export const CREATE_INTERN_DOCUMENTS_FAILURE = "CREATE_INTERN_DOCUMENTS_FAILURE";

export const GET_INTERN_DOCUMENTS_REQUEST = "GET_INTERN_DOCUMENTS_REQUEST";
export const GET_INTERN_DOCUMENTS_SUCCESS = "GET_INTERN_DOCUMENTS_SUCCESS";
export const GET_INTERN_DOCUMENTS_FAILURE = "GET_INTERN_DOCUMENTS_FAILURE";

export const UPDATE_INTERN_DOCUMENTS_REQUEST = "UPDATE_INTERN_DOCUMENTS_REQUEST";
export const UPDATE_INTERN_DOCUMENTS_SUCCESS = "UPDATE_INTERN_DOCUMENTS_SUCCESS";
export const UPDATE_INTERN_DOCUMENTS_FAILURE = "UPDATE_INTERN_DOCUMENTS_FAILURE";

export const GET_INTERN_DOCUMENTS_BY_TYPE_DOCUMENT_REQUEST="GET_INTERN_DOCUMENTS_BY_TYPE_DOCUMENT_REQUEST";
export const GET_INTERN_DOCUMENTS_BY_TYPE_DOCUMENT_SUCCESS="GET_INTERN_DOCUMENTS_BY_TYPE_DOCUMENT_SUCCESS";
export const GET_INTERN_DOCUMENTS_BY_TYPE_DOCUMENT_FAILURE="GET_INTERN_DOCUMENTS_BY_TYPE_DOCUMENT_FAILURE";

export const GET_MOVEMENTS_TO_ANALYZE_REQUEST = "GET_MOVEMENTS_TO_ANALYZE_REQUEST";
export const GET_MOVEMENTS_TO_ANALYZE_SUCCESS = "GET_MOVEMENTS_TO_ANALYZE_SUCCESS";
export const GET_MOVEMENTS_TO_ANALYZE_FAILURE = "GET_MOVEMENTS_TO_ANALYZE_FAILURE";

export const GET_MOVEMENTS_ADVANCED_SEARCH_REQUEST = "GET_MOVEMENTS_ADVANCED_SEARCH_REQUEST";
export const GET_MOVEMENTS_ADVANCED_SEARCH_SUCCESS = "GET_MOVEMENTS_ADVANCED_SEARCH_SUCCESS";
export const GET_MOVEMENTS_ADVANCED_SEARCH_FAILURE = "GET_MOVEMENTS_ADVANCED_SEARCH_FAILURE";

export const CLEAN_DATA_MOVEMENTS = "CLEAN_DATA_MOVEMENTS";

export const LOAD_ALL_USERS_REQUEST = "LOAD_ALL_USERS_REQUEST";
export const LOAD_ALL_USERS_SUCCESS = "LOAD_ALL_USERS_SUCCESS";
export const LOAD_ALL_USERS_FAILURE = "LOAD_ALL_USERS_FAILURE";

export const LOAD_ALL_OFFICES_REQUEST = "LOAD_ALL_OFFICES_REQUEST";
export const LOAD_ALL_OFFICES_SUCCESS = "LOAD_ALL_OFFICES_SUCCESS";
export const LOAD_ALL_OFFICES_FAILURE = "LOAD_ALL_OFFICES_FAILURE";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE";

export const LOAD_USER_BY_ID_REQUEST = "LOAD_USER_BY_ID_REQUEST";
export const LOAD_USER_BY_ID_SUCCESS = "LOAD_USER_BY_ID_SUCCESS";
export const LOAD_USER_BY_ID_FAILURE = "LOAD_USER_BY_ID_FAILURE";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE";

export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAILURE = "CREATE_USER_FAILURE";

export const UPDATE_OFFICE_REQUEST = "UPDATE_OFFICE_REQUEST";
export const UPDATE_OFFICE_SUCCESS = "UPDATE_OFFICE_SUCCESS";
export const UPDATE_OFFICE_FAILURE = "UPDATE_OFFICE_FAILURE";

export const LOAD_OFFICE_BY_ID_REQUEST = "LOAD_OFFICE_BY_ID_REQUEST";
export const LOAD_OFFICE_BY_ID_SUCCESS = "LOAD_OFFICE_BY_ID_SUCCESS";
export const LOAD_OFFICE_BY_ID_FAILURE = "LOAD_OFFICE_BY_ID_FAILURE";

export const DELETE_OFFICE_REQUEST = "DELETE_OFFICE_REQUEST";
export const DELETE_OFFICE_SUCCESS = "DELETE_OFFICE_SUCCESS";
export const DELETE_OFFICE_FAILURE = "DELETE_OFFICE_FAILURE";

export const CREATE_OFFICE_REQUEST = "CREATE_OFFICE_REQUEST";
export const CREATE_OFFICE_SUCCESS = "CREATE_OFFICE_SUCCESS";
export const CREATE_OFFICE_FAILURE = "CREATE_OFFICE_FAILURE";

