export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const STORE_LOGGED_IN_USER = 'STORE_LOGGED_IN_USER'

export const VALIDATE_ACCESS = 'VALIDATE_ACCESS';

export const GET_VIEW2_DATA_REQUEST = 'GET_VIEW2_DATA_REQUEST';
export const GET_VIEW2_DATA_SUCCESS = 'GET_VIEW2_DATA_SUCCESS';
export const GET_VIEW2_DATA_FAILURE = 'GET_VIEW2_DATA_FAILURE';

export const GET_INITIAL_DATA = 'GET_INITIAL_DATA';

export const INSERT_MOVEMENTS_REQUEST = "INSERT_MOVEMENTS_REQUEST";
export const INSERT_MOVEMENTS_SUCCESS = "INSERT_MOVEMENTS_SUCCESS";
export const INSERT_MOVEMENTS_FAILURE = "INSERT_MOVEMENTS_FAILURE";

export const GET_MOVEMENTS_REQUEST = "GET_MOVEMENTS_REQUEST";
export const GET_MOVEMENTS_SUCCESS = "GET_MOVEMENTS_SUCCESS";
export const GET_MOVEMENTS_FAILURE = "GET_MOVEMENTS_FAILURE";
export const CLEAN_MOVEMENTS_LIST = "CLEAN_MOVEMENTS_LIST";

export const DELETE_MOVEMENT_REQUEST = "DELETE_MOVEMENT_REQUEST";
export const DELETE_MOVEMENT_SUCCESS = "DELETE_MOVEMENT_SUCCESS";
export const DELETE_MOVEMENT_FAILURE = "DELETE_MOVEMENT_FAILURE";

export const GET_TYPE_DOCUMENTS_REQUEST = "GET_TYPE_DOCUMENTS_REQUEST";
export const GET_TYPE_DOCUMENTS_SUCCESS = "GET_TYPE_DOCUMENTS_SUCCESS";
export const GET_TYPE_DOCUMENTS_FAILURE = "GET_TYPE_DOCUMENTS_FAILURE";

export const GET_CORRELATIVE_MAX_REQUEST = "GET_CORRELATIVE_MAX_REQUEST";
export const GET_CORRELATIVE_MAX_SUCCESS = "GET_CORRELATIVE_MAX_SUCCESS";

export const USER_BOSS_OFFICE_REQUEST = "USER_BOSS_OFFICE_REQUEST";
export const USER_BOSS_OFFICE_SUCCESS = "USER_BOSS_OFFICE_SUCCESS";

export const GET_CIRCULAR_DOCUMENTS_REQUEST = "GET_CIRCULAR_DOCUMENTS_REQUEST";
export const GET_CIRCULAR_DOCUMENTS_SUCCESS = "GET_CIRCULAR_DOCUMENTS_SUCCESS";
export const GET_CIRCULAR_DOCUMENTS_FAILURE = "GET_CIRCULAR_DOCUMENTS_FAILURE";

export const CREATE_CIRCULAR_DOCUMENTS_REQUEST = "CREATE_CIRCULAR_DOCUMENTS_REQUEST";
export const CREATE_CIRCULAR_DOCUMENTS_SUCCESS = "CREATE_CIRCULAR_DOCUMENTS_SUCCESS";
export const CREATE_CIRCULAR_DOCUMENTS_FAILURE = "CREATE_CIRCULAR_DOCUMENTS_FAILURE";
