export const listDataTotal = [{
    "id": "1",
    "num_tram": "01115-FCA-2019",
    "movimiento": "23",
    "destino": "OGPL-OFICINA DE RACIONALIZACION",
    "fech_envio": "02/07/2019 10:07:33",
    "indic": "ATENCION",
    "observacion": "SIN DOC",
    "estado": "EN PROCESO",
    "docum_nomb": "SIN DOCU",
    "check": false
  },
    {
      "id": "2",
      "num_tram": "01158-SG-2019",
      "movimiento": "5",
      "destino": "OGPL-OFICINA DE PRESUPUESTO",
      "fech_envio": "04/11/2019 15:07:33",
      "indic": "ATENCION",
      "observacion": "SIN DOC",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "3",
      "num_tram": "01179-FO-2019",
      "movimiento": "11",
      "destino": "OGPL-OFICINA DE CENTRO PRODUCCION",
      "fech_envio": "02/07/2019 10:07:33",
      "indic": "ATENCION",
      "observacion": "SIN DOC",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "4",
      "num_tram": "01183-DGA-2019",
      "movimiento": "24",
      "destino": "OGPL-OFICINA DE ESTADISTICA",
      "fech_envio": "02/07/2019 10:07:33",
      "indic": "ATENCION",
      "observacion": "SIN DOC",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "5",
      "num_tram": "01161-OGPL-2019",
      "movimiento": "41",
      "destino": "OGPL-OFICINA DE RACIONALIZACION",
      "fech_envio": "02/07/2019 10:07:33",
      "indic": "ATENCION",
      "observacion": "OFICIO(S) N 01124-OGPL-2019",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "6",
      "num_tram": "01116-DGA-2019",
      "movimiento": "2",
      "destino": "OGPL-OFICINA DE CENTRO PRODUCCION",
      "fech_envio": "02/07/2019 10:07:33",
      "indic": "ATENCION",
      "observacion": "SIN DOC",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "7",
      "num_tram": "01115-FCA-2019",
      "movimiento": "5",
      "destino": "OGPL-OFICINA DE PRESUPUESTO",
      "fech_envio": "02/07/2019 10:07:33",
      "indic": "ATENCION",
      "observacion": "SIN DOC",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "8",
      "num_tram": "01166-DGA-2019",
      "movimiento": "12",
      "destino": "OGPL-OFICINA DE RACIONALIZACION",
      "fech_envio": "02/07/2019 10:07:33",
      "indic": "ATENCION",
      "observacion": "SIN DOC",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "9",
      "num_tram": "01155-FCA-2019",
      "movimiento": "65",
      "destino": "OGPL-OFICINA DE CENTRO PRODUCCION",
      "fech_envio": "02/07/2019 10:07:33",
      "indic": "ATENCION",
      "observacion": "SIN DOC",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "10",
      "num_tram": "01196-DGA-2019",
      "movimiento": "23",
      "destino": "OGPL-OFICINA DE PRESUPUESTO",
      "fech_envio": "02/07/2019 10:07:33",
      "indic": "ATENCION",
      "observacion": "SIN DOC",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "11",
      "num_tram": "01183-DGA-2019",
      "movimiento": "9",
      "destino": "OGPL-OFICINA DE CENTRO PRODUCCION",
      "fech_envio": "02/07/2019 10:07:33",
      "indic": "ATENCION",
      "observacion": "SIN DOC",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "12",
      "num_tram": "01173-FCA-2019",
      "movimiento": "23",
      "destino": "OGPL-OFICINA DE PRESUPUESTO",
      "fech_envio": "02/07/2019 10:07:33",
      "indic": "ATENCION",
      "observacion": "SIN DOC",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "13",
      "num_tram": "011553-DGA-2019",
      "movimiento": "4",
      "destino": "OGPL-OFICINA DE RACIONALIZACION",
      "fech_envio": "02/07/2019 10:07:33",
      "indic": "ATENCION",
      "observacion": "SIN DOC",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "14",
      "num_tram": "01172-FCA-2019",
      "movimiento": "17",
      "destino": "OGPL-OFICINA DE CENTRO PRODUCCION",
      "fech_envio": "02/07/2019 10:07:33",
      "indic": "ATENCION",
      "observacion": "SIN DOC",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "15",
      "num_tram": "01129-DGA-2019",
      "movimiento": "20",
      "destino": "OGPL-OFICINA DE PRESUPUESTO",
      "fech_envio": "02/07/2019 10:07:33",
      "indic": "ATENCION",
      "observacion": "SIN DOC",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "16",
      "num_tram": "02111-FCA-2019",
      "movimiento": "23",
      "destino": "OGPL-OFICINA DE RACIONALIZACION",
      "fech_envio": "02/07/2019 10:07:33",
      "indic": "ATENCION",
      "observacion": "SIN DOC",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "17",
      "num_tram": "02222-SG-2019",
      "movimiento": "5",
      "destino": "OGPL-OFICINA DE PRESUPUESTO",
      "fech_envio": "04/11/2019 15:07:33",
      "indic": "ATENCION",
      "observacion": "SIN DOC",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "18",
      "num_tram": "02333-FO-2019",
      "movimiento": "11",
      "destino": "OGPL-OFICINA DE CENTRO PRODUCCION",
      "fech_envio": "02/07/2019 10:07:33",
      "indic": "ATENCION",
      "observacion": "SIN DOC",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "19",
      "num_tram": "02444-DGA-2019",
      "movimiento": "24",
      "destino": "OGPL-OFICINA DE ESTADISTICA",
      "fech_envio": "02/07/2019 10:07:33",
      "indic": "ATENCION",
      "observacion": "SIN DOC",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "20",
      "num_tram": "02555-OGPL-2019",
      "movimiento": "41",
      "destino": "OGPL-OFICINA DE RACIONALIZACION",
      "fech_envio": "02/07/2019 10:07:33",
      "indic": "ATENCION",
      "observacion": "OFICIO(S) N 01124-OGPL-2019",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "21",
      "num_tram": "02666-DGA-2019",
      "movimiento": "2",
      "destino": "OGPL-OFICINA DE CENTRO PRODUCCION",
      "fech_envio": "02/07/2019 10:07:33",
      "indic": "ATENCION",
      "observacion": "SIN DOC",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "22",
      "num_tram": "02777-FCA-2019",
      "movimiento": "5",
      "destino": "OGPL-OFICINA DE PRESUPUESTO",
      "fech_envio": "02/07/2019 10:07:33",
      "indic": "ATENCION",
      "observacion": "SIN DOC",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "23",
      "num_tram": "02888-DGA-2019",
      "movimiento": "12",
      "destino": "OGPL-OFICINA DE RACIONALIZACION",
      "fech_envio": "02/07/2019 10:07:33",
      "indic": "ATENCION",
      "observacion": "SIN DOC",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "24",
      "num_tram": "02999-FCA-2019",
      "movimiento": "65",
      "destino": "OGPL-OFICINA DE CENTRO PRODUCCION",
      "fech_envio": "02/07/2019 10:07:33",
      "indic": "ATENCION",
      "observacion": "SIN DOC",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "25",
      "num_tram": "02100-DGA-2019",
      "movimiento": "23",
      "destino": "OGPL-OFICINA DE PRESUPUESTO",
      "fech_envio": "02/07/2019 10:07:33",
      "indic": "ATENCION",
      "observacion": "SIN DOC",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "26",
      "num_tram": "02101-DGA-2019",
      "movimiento": "9",
      "destino": "OGPL-OFICINA DE CENTRO PRODUCCION",
      "fech_envio": "02/07/2019 10:07:33",
      "indic": "ATENCION",
      "observacion": "SIN DOC",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "27",
      "num_tram": "02102-FCA-2019",
      "movimiento": "23",
      "destino": "OGPL-OFICINA DE PRESUPUESTO",
      "fech_envio": "02/07/2019 10:07:33",
      "indic": "ATENCION",
      "observacion": "SIN DOC",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "28",
      "num_tram": "02103-DGA-2019",
      "movimiento": "4",
      "destino": "OGPL-OFICINA DE RACIONALIZACION",
      "fech_envio": "02/07/2019 10:07:33",
      "indic": "ATENCION",
      "observacion": "SIN DOC",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "29",
      "num_tram": "02104-FCA-2019",
      "movimiento": "17",
      "destino": "OGPL-OFICINA DE CENTRO PRODUCCION",
      "fech_envio": "02/07/2019 10:07:33",
      "indic": "ATENCION",
      "observacion": "SIN DOC",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "30",
      "num_tram": "02105-DGA-2019",
      "movimiento": "20",
      "destino": "OGPL-OFICINA DE PRESUPUESTO",
      "fech_envio": "02/07/2019 10:07:33",
      "indic": "ATENCION",
      "observacion": "SIN DOC",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "31",
      "num_tram": "03111-FCA-2019",
      "movimiento": "23",
      "destino": "OGPL-OFICINA DE RACIONALIZACION",
      "fech_envio": "02/07/2019 10:07:33",
      "indic": "ATENCION",
      "observacion": "SIN DOC",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "32",
      "num_tram": "03222-SG-2019",
      "movimiento": "5",
      "destino": "OGPL-OFICINA DE PRESUPUESTO",
      "fech_envio": "04/11/2019 15:07:33",
      "indic": "ATENCION",
      "observacion": "SIN DOC",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "33",
      "num_tram": "03333-FO-2019",
      "movimiento": "11",
      "destino": "OGPL-OFICINA DE CENTRO PRODUCCION",
      "fech_envio": "02/07/2019 10:07:33",
      "indic": "ATENCION",
      "observacion": "SIN DOC",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "34",
      "num_tram": "03444-DGA-2019",
      "movimiento": "24",
      "destino": "OGPL-OFICINA DE ESTADISTICA",
      "fech_envio": "02/07/2019 10:07:33",
      "indic": "ATENCION",
      "observacion": "SIN DOC",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "35",
      "num_tram": "03555-OGPL-2019",
      "movimiento": "41",
      "destino": "OGPL-OFICINA DE RACIONALIZACION",
      "fech_envio": "02/07/2019 10:07:33",
      "indic": "ATENCION",
      "observacion": "OFICIO(S) N 01124-OGPL-2019",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    }]

export const listData_1 =
  [{
    "id": "1",
    "num_tram": "01115-FCA-2019",
    "movimiento": "23",
    "destino": "OGPL-OFICINA DE RACIONALIZACION",
    "fech_envio": "02/07/2019 10:07:33",
    "indic": "ATENCION",
    "observacion": "SIN DOC",
    "estado": "EN PROCESO",
    "docum_nomb": "SIN DOCU",
    "check": false
  },
    {
      "id": "2",
      "num_tram": "01158-SG-2019",
      "movimiento": "5",
      "destino": "OGPL-OFICINA DE PRESUPUESTO",
      "fech_envio": "04/11/2019 15:07:33",
      "indic": "ATENCION",
      "observacion": "SIN DOC",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "3",
      "num_tram": "01179-FO-2019",
      "movimiento": "11",
      "destino": "OGPL-OFICINA DE CENTRO PRODUCCION",
      "fech_envio": "02/07/2019 10:07:33",
      "indic": "ATENCION",
      "observacion": "SIN DOC",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "4",
      "num_tram": "01183-DGA-2019",
      "movimiento": "24",
      "destino": "OGPL-OFICINA DE ESTADISTICA",
      "fech_envio": "02/07/2019 10:07:33",
      "indic": "ATENCION",
      "observacion": "SIN DOC",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "5",
      "num_tram": "01161-OGPL-2019",
      "movimiento": "41",
      "destino": "OGPL-OFICINA DE RACIONALIZACION",
      "fech_envio": "02/07/2019 10:07:33",
      "indic": "ATENCION",
      "observacion": "OFICIO(S) N 01124-OGPL-2019",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "6",
      "num_tram": "01116-DGA-2019",
      "movimiento": "2",
      "destino": "OGPL-OFICINA DE CENTRO PRODUCCION",
      "fech_envio": "02/07/2019 10:07:33",
      "indic": "ATENCION",
      "observacion": "SIN DOC",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "7",
      "num_tram": "01115-FCA-2019",
      "movimiento": "5",
      "destino": "OGPL-OFICINA DE PRESUPUESTO",
      "fech_envio": "02/07/2019 10:07:33",
      "indic": "ATENCION",
      "observacion": "SIN DOC",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "8",
      "num_tram": "01166-DGA-2019",
      "movimiento": "12",
      "destino": "OGPL-OFICINA DE RACIONALIZACION",
      "fech_envio": "02/07/2019 10:07:33",
      "indic": "ATENCION",
      "observacion": "SIN DOC",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "9",
      "num_tram": "01155-FCA-2019",
      "movimiento": "65",
      "destino": "OGPL-OFICINA DE CENTRO PRODUCCION",
      "fech_envio": "02/07/2019 10:07:33",
      "indic": "ATENCION",
      "observacion": "SIN DOC",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "10",
      "num_tram": "01196-DGA-2019",
      "movimiento": "23",
      "destino": "OGPL-OFICINA DE PRESUPUESTO",
      "fech_envio": "02/07/2019 10:07:33",
      "indic": "ATENCION",
      "observacion": "SIN DOC",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "11",
      "num_tram": "01183-DGA-2019",
      "movimiento": "9",
      "destino": "OGPL-OFICINA DE CENTRO PRODUCCION",
      "fech_envio": "02/07/2019 10:07:33",
      "indic": "ATENCION",
      "observacion": "SIN DOC",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "12",
      "num_tram": "01173-FCA-2019",
      "movimiento": "23",
      "destino": "OGPL-OFICINA DE PRESUPUESTO",
      "fech_envio": "02/07/2019 10:07:33",
      "indic": "ATENCION",
      "observacion": "SIN DOC",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "13",
      "num_tram": "011553-DGA-2019",
      "movimiento": "4",
      "destino": "OGPL-OFICINA DE RACIONALIZACION",
      "fech_envio": "02/07/2019 10:07:33",
      "indic": "ATENCION",
      "observacion": "SIN DOC",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "14",
      "num_tram": "01172-FCA-2019",
      "movimiento": "17",
      "destino": "OGPL-OFICINA DE CENTRO PRODUCCION",
      "fech_envio": "02/07/2019 10:07:33",
      "indic": "ATENCION",
      "observacion": "SIN DOC",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "15",
      "num_tram": "01129-DGA-2019",
      "movimiento": "20",
      "destino": "OGPL-OFICINA DE PRESUPUESTO",
      "fech_envio": "02/07/2019 10:07:33",
      "indic": "ATENCION",
      "observacion": "SIN DOC",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    }]

export const listData_2 =
  [{
    "id": "16",
    "num_tram": "02111-FCA-2019",
    "movimiento": "23",
    "destino": "OGPL-OFICINA DE RACIONALIZACION",
    "fech_envio": "02/07/2019 10:07:33",
    "indic": "ATENCION",
    "observacion": "SIN DOC",
    "estado": "EN PROCESO",
    "docum_nomb": "SIN DOCU",
    "check": false
  },
    {
      "id": "17",
      "num_tram": "02222-SG-2019",
      "movimiento": "5",
      "destino": "OGPL-OFICINA DE PRESUPUESTO",
      "fech_envio": "04/11/2019 15:07:33",
      "indic": "ATENCION",
      "observacion": "SIN DOC",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "18",
      "num_tram": "02333-FO-2019",
      "movimiento": "11",
      "destino": "OGPL-OFICINA DE CENTRO PRODUCCION",
      "fech_envio": "02/07/2019 10:07:33",
      "indic": "ATENCION",
      "observacion": "SIN DOC",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "19",
      "num_tram": "02444-DGA-2019",
      "movimiento": "24",
      "destino": "OGPL-OFICINA DE ESTADISTICA",
      "fech_envio": "02/07/2019 10:07:33",
      "indic": "ATENCION",
      "observacion": "SIN DOC",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "20",
      "num_tram": "02555-OGPL-2019",
      "movimiento": "41",
      "destino": "OGPL-OFICINA DE RACIONALIZACION",
      "fech_envio": "02/07/2019 10:07:33",
      "indic": "ATENCION",
      "observacion": "OFICIO(S) N 01124-OGPL-2019",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "21",
      "num_tram": "02666-DGA-2019",
      "movimiento": "2",
      "destino": "OGPL-OFICINA DE CENTRO PRODUCCION",
      "fech_envio": "02/07/2019 10:07:33",
      "indic": "ATENCION",
      "observacion": "SIN DOC",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "22",
      "num_tram": "02777-FCA-2019",
      "movimiento": "5",
      "destino": "OGPL-OFICINA DE PRESUPUESTO",
      "fech_envio": "02/07/2019 10:07:33",
      "indic": "ATENCION",
      "observacion": "SIN DOC",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "23",
      "num_tram": "02888-DGA-2019",
      "movimiento": "12",
      "destino": "OGPL-OFICINA DE RACIONALIZACION",
      "fech_envio": "02/07/2019 10:07:33",
      "indic": "ATENCION",
      "observacion": "SIN DOC",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "24",
      "num_tram": "02999-FCA-2019",
      "movimiento": "65",
      "destino": "OGPL-OFICINA DE CENTRO PRODUCCION",
      "fech_envio": "02/07/2019 10:07:33",
      "indic": "ATENCION",
      "observacion": "SIN DOC",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "25",
      "num_tram": "02100-DGA-2019",
      "movimiento": "23",
      "destino": "OGPL-OFICINA DE PRESUPUESTO",
      "fech_envio": "02/07/2019 10:07:33",
      "indic": "ATENCION",
      "observacion": "SIN DOC",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "26",
      "num_tram": "02101-DGA-2019",
      "movimiento": "9",
      "destino": "OGPL-OFICINA DE CENTRO PRODUCCION",
      "fech_envio": "02/07/2019 10:07:33",
      "indic": "ATENCION",
      "observacion": "SIN DOC",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "27",
      "num_tram": "02102-FCA-2019",
      "movimiento": "23",
      "destino": "OGPL-OFICINA DE PRESUPUESTO",
      "fech_envio": "02/07/2019 10:07:33",
      "indic": "ATENCION",
      "observacion": "SIN DOC",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "28",
      "num_tram": "02103-DGA-2019",
      "movimiento": "4",
      "destino": "OGPL-OFICINA DE RACIONALIZACION",
      "fech_envio": "02/07/2019 10:07:33",
      "indic": "ATENCION",
      "observacion": "SIN DOC",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "29",
      "num_tram": "02104-FCA-2019",
      "movimiento": "17",
      "destino": "OGPL-OFICINA DE CENTRO PRODUCCION",
      "fech_envio": "02/07/2019 10:07:33",
      "indic": "ATENCION",
      "observacion": "SIN DOC",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "30",
      "num_tram": "02105-DGA-2019",
      "movimiento": "20",
      "destino": "OGPL-OFICINA DE PRESUPUESTO",
      "fech_envio": "02/07/2019 10:07:33",
      "indic": "ATENCION",
      "observacion": "SIN DOC",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    }]

export const listData_3 =[{
    "id": "31",
    "num_tram": "03111-FCA-2019",
    "movimiento": "23",
    "destino": "OGPL-OFICINA DE RACIONALIZACION",
    "fech_envio": "02/07/2019 10:07:33",
    "indic": "ATENCION",
    "observacion": "SIN DOC",
    "estado": "EN PROCESO",
    "docum_nomb": "SIN DOCU",
    "check": false
  },
    {
      "id": "32",
      "num_tram": "03222-SG-2019",
      "movimiento": "5",
      "destino": "OGPL-OFICINA DE PRESUPUESTO",
      "fech_envio": "04/11/2019 15:07:33",
      "indic": "ATENCION",
      "observacion": "SIN DOC",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "33",
      "num_tram": "03333-FO-2019",
      "movimiento": "11",
      "destino": "OGPL-OFICINA DE CENTRO PRODUCCION",
      "fech_envio": "02/07/2019 10:07:33",
      "indic": "ATENCION",
      "observacion": "SIN DOC",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "34",
      "num_tram": "03444-DGA-2019",
      "movimiento": "24",
      "destino": "OGPL-OFICINA DE ESTADISTICA",
      "fech_envio": "02/07/2019 10:07:33",
      "indic": "ATENCION",
      "observacion": "SIN DOC",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    },
    {
      "id": "35",
      "num_tram": "03555-OGPL-2019",
      "movimiento": "41",
      "destino": "OGPL-OFICINA DE RACIONALIZACION",
      "fech_envio": "02/07/2019 10:07:33",
      "indic": "ATENCION",
      "observacion": "OFICIO(S) N 01124-OGPL-2019",
      "estado": "EN PROCESO",
      "docum_nomb": "SIN DOCU",
      "check": false
    }]

export const lista_circulares = [
  {
    "id": "31",
    "correlativo": "03321-DGA-2019",
    "asunto": "ASUNTO DE CIRCULAR QUE A VECES SUELE SER MUY LARGO ASI QUE HAY QUE PROBAR CUAN LARGO PUEDE SER",
    "area_resp": "OGPL-OFICINA DE PRESUPUESTO",
    "fech_envio": "02/07/2019 10:07:33",
    "firma": "L. PEDRO VERANO",
    "responsable": "SANDOVAL CATHERINE",
    "check": false
  },
  {
    "id": "32",
    "correlativo": "03521-UGA-2019",
    "asunto": "ASUNTO DE CIRCULAR QUE A VECES SUELE SER MUY LARGO ASI QUE HAY QUE PROBAR CUAN LARGO PUEDE SER",
    "area_resp": "OGPL-OFICINA DE PRESUPUESTO",
    "fech_envio": "02/07/2019 10:07:33",
    "firma": "L. PEDRO VERANO",
    "responsable": "SANDOVAL CATHERINE",
    "check": false
  },
  {
    "id": "33",
    "correlativo": "01231-FGO-2019",
    "asunto": "ASUNTO DE CIRCULAR QUE A VECES SUELE SER MUY LARGO ASI QUE HAY QUE PROBAR CUAN LARGO PUEDE SER",
    "area_resp": "OGPL-OFICINA DE RACIONALIZACION",
    "fech_envio": "02/07/2019 10:07:33",
    "firma": "L. PEDRO VERANO",
    "responsable": "SANDOVAL CATHERINE",
    "check": false
  },
  {
    "id": "34",
    "correlativo": "05341-DGA-2019",
    "asunto": "ASUNTO DE CIRCULAR QUE A VECES SUELE SER MUY LARGO ASI QUE HAY QUE PROBAR CUAN LARGO PUEDE SER",
    "area_resp": "OGPL-OFICINA DE RACIONALIZACION",
    "fech_envio": "02/07/2019 10:07:33",
    "firma": "L. PEDRO VERANO",
    "responsable": "SANDOVAL CATHERINE",
    "check": false
  },
  {
    "id": "35",
    "correlativo": "42211-GUY-2019",
    "asunto": "ASUNTO DE CIRCULAR ",
    "area_resp": "OGPL-OFICINA DE RACIONALIZACION",
    "fech_envio": "02/07/2019 10:07:33",
    "firma": "L. PEDRO VERANO",
    "responsable": "SANDOVAL CATHERINE",
    "check": false
  },
  {
    "id": "36",
    "correlativo": "03321-DGA-2019",
    "asunto": "ASUNTO DE CIRCULAR QUE A VECES SUELE SER MUY LARGO ASI QUE HAY QUE PROBAR CUAN LARGO PUEDE SER",
    "area_resp": "OGPL-OFICINA DE ESTADISTICA E INFORMATICA",
    "fech_envio": "02/07/2019 10:07:33",
    "firma": "L. PEDRO VERANO",
    "responsable": "SANDOVAL CATHERINE",
    "check": false
  },
  {
    "id": "37",
    "correlativo": "03321-DGA-2019",
    "asunto": "ASUNTO DE CIRCULAR ",
    "area_resp": "OGPL-OFICINA DE ESTADISTICA E INFORMATICA",
    "fech_envio": "02/07/2019 10:07:33",
    "firma": "L. PEDRO VERANO",
    "responsable": "SANDOVAL CATHERINE",
    "check": false
  },
  {
    "id": "38",
    "correlativo": "03321-DGA-2019",
    "asunto": "ASUNTO DE CIRCULAR QUE A VECES SUELE SER MUY LARGO ASI QUE HAY QUE PROBAR CUAN LARGO PUEDE SER",
    "area_resp": "OGPL-OFICINA DE RACIONALIZACION",
    "fech_envio": "02/07/2019 10:07:33",
    "firma": "L. PEDRO VERANO",
    "responsable": "SANDOVAL CATHERINE",
    "check": false
  },
  {
    "id": "31",
    "correlativo": "03321-DGA-2019",
    "asunto": "ASUNTO DE CIRCULAR ",
    "area_resp": "OGPL-OFICINA DE CENTRO PRODUCCION",
    "fech_envio": "02/07/2019 10:07:33",
    "firma": "L. PEDRO VERANO",
    "responsable": "SANDOVAL CATHERINE",
    "check": false
  },
  {
    "id": "39",
    "correlativo": "03321-DGA-2019",
    "asunto": "ASUNTO DE CIRCULAR QUE A VECES SUELE SER MUY LARGO ASI QUE HAY QUE PROBAR CUAN LARGO PUEDE SER",
    "area_resp": "OGPL-OFICINA DE RACIONALIZACION",
    "fech_envio": "02/07/2019 10:07:33",
    "firma": "L. PEDRO VERANO",
    "responsable": "SANDOVAL CATHERINE",
    "check": false
  }

]